# Author: <your name>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: traffic-pipeline:latest
          imagePullPolicy: IfNotPresent
          args: ["scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-config
            - secretRef:
                name: airflow-secret
